-- local config = {
--     cmd = { vim.fn.stdpath('data') .. "/mason/bin/jdtls" },
--     root_dir = vim.fs.dirname(vim.fs.find({'gradlew', '.gradlew', '.git', 'mvnw'}, { upward = true })[1]),
--     -- root_dir = vim.fs.root(0, {".git", "mvnw", "gradlew"})
--
-- }
-- require('jdtls').start_or_attach(config)
